logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.68.132 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: guest
    password: guest
    virtual-host: /
    #控制消息预取
    listener:
      simple:
        prefetch: 1 #每次只能获取一条消息，处理完才能获取下一条消息