#挡在指定微服务的前面，像Nginx一样，加入gateway之后，可以通过localhost:10010/user/**访问到user-service，
#也可以通过localhost:10010/order/**访问到order-service

server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.68.132:8848
    #路由配置
    gateway:
      routes:
        - id: user-service #路由标示，唯一
          uri: lb://user-service #路由的目标地址
          #路由断言，判断请求是否符合规则
          predicates:
            - Path=/user/** #路径断言，判断路径是否以/user开头，如果是则符合
          #过滤器
          filters:
            - AddRequestHeader=Talk,nice to meet you! #给每个发往user-service的请求，都加个请求头
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
