server:
  port: 8081

spring:
  #bootstrap.yml中配置过后这里就可以注释了
#  application:
#    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud2022?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 870814
    driver-class-name: com.mysql.jdbc.Driver
  #bootstrap.yml中配置过后这里就可以注释了
#  cloud:
#    nacos:
#      server-addr: 192.168.68.132:8848
#      discovery:
#        #可以配置不同的集群名称，比如1，2号Provider配置“南京”，3，4号配置“上海”
#        cluster-name: NJ


mybatis:
  type-aliases-package: cn.wy.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.wy: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka的地址信息（改用Nacos后就不再需要eureka的配置了）
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka