server:
  port: 10086

spring:
  application:
    name: eureka-server #eureka的服务名称

#eureka虽然是注册中心，但自身也是一个微服务，有时需要自己将自己注册到eureka中（比如搭建eureka集群时）
eureka:
  client:
    service-url: #eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka